service: dispatch-realtor-api-requests

custom:
  secrets: ${file(secrets.json)}

provider:
  lambdaHashingVersion: "20201221"
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.secrets.NODE_ENV}
  region: eu-west-2
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    REALTOR_API_KEY: ${self:custom.secrets.REALTOR_API_KEY}
    DOMAIN: ${self:custom.secrets.DOMAIN}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
          Resource: "*"
  apiGateway:
    shouldStartNameWithService: true

functions:
  send:
    handler: handler.send
    events:
      - http:
          path: send
          method: get
          cors: true
